# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;

    - name: Test with pytest
      run: |
        pytest
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Deploy only if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload Python Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python-build
          path: https://github.com/swapnilverma0209/savePythonArtifacts.git/build/
